# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://smily.space
date_format: "ordinal"
title: Smily
subtitle: "微笑面对人生，诚实面对自己"
description: "阮振华的个人博客"
keywords: 阮振华, ruanzh, rzh0001, Smily
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
music_id: 27588486
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Smily
organization: ...
organization_url: ...
github_username: rzh0001
location: Xiamen, China
email: rzh0001@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-publish
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: rzh0001/rzh0001.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
    # username: rzh0001
# https://gentie.163.com
# netease_gentie:
    # productKey: 560ed243b708465d82d5a0a5f3b83da1
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: rzh0001
    repo: blog-comments
    oauth:
        client_id: a12c4fbc837c2aa6e217
        client_secret: 372b2d5c3585a07486fed60cceb565853096cdfe
# 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-101493172-1
